let productData = [
  {
    id: 1,
    title: "Apple iPhone 13 Pro (512GB) - Sierra Blue",
    price: { offer: "98000.00", mrp: "120000.00", exchange: "16000.00" },
    emi: "7,456",
    image: "https://i.ibb.co/W2b1fdX/iphone.png",
    description: [
      "17 cm (6.7-inch) Super Retina XDR display with ProMotion for a faster, more responsive feel",

      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Pro camera system with new 12MP Telephoto, Wide and Ultra Wide cameras; LiDAR Scanner; 6x optical zoom range; macro photography; Photographic Styles, ProRes video, Smart HDR 4, Night mode, Apple ProRAW, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording A15 Bionic chip for lightning - fast performance",
      "Up to 28 hours of video playback, the best battery life ever in an iPhone Durable design with Ceramic Shield",
      "Industry-leading IP68 water resistance",
      "iOS 15 packs new features to do more with iPhone than ever before",
      " Supports MagSafe accessories for easy attachment and faster wireless charging",
      "Industry-leading IP68 water resistance",
      "form_factor:Smartphone,operating_system:iOS 14",
    ],
    otherOffer: "₹5000 additional discount on exchange",
    rating: {
      rate: 4,
      count: 654,
      answers: 215,
    },
  },
  {
    id: 2,
    title: "Amazfit Bip 3 Smart Watch with 1.69 Large Color Display",
    price: { offer: "4000.00", mrp: "4500.00", exchange: "500.00" },
    emi: "500",
    image: "https://i.ibb.co/fCsdT4L/smartwatch.png",
    description: [
      "1.69 inch Large Color Display",
      "2 Weeks' Battery Life",
      "5 ATM Water-resistance",
      "60 Sports Modes",
      "Blood-oxygen Saturation Measurement",
      "50+ Vibrant Watch Faces",
      "Super Slim & Light Body",
      "Monitoring of Heart Rate, Stress Levels & Sleep",
      "PAI Health Assessment System",
    ],
    otherOffer: "Amazon Fulfilled | FREE Delivery.",
    rating: {
      rate: 3,
      count: 1454,
      answers: 45,
    },
  },
  {
    id: 3,
    title:
      "Samsung 138 cm (55 inches) 4K Ultra HD Smart NEO QLED TV QA55QN90BAKLXL (Titan Black)",
    price: { offer: "72000.00", mrp: "80000.00", exchange: "10000.00" },
    emi: "5,456",
    image: "https://i.ibb.co/0jsdTwn/samsungtv.png",
    description: [
      "Resolution : 4K Ultra HD (3840 x 2160) Resolution || Refresh Rate : 100 Hertz",
      "Connectivity: 4 HDMI ports to connect set top box || Blu-ray speakers or a gaming console || 2 USB ports to connect hard drives or other USB devices",
      "Sound: 60 Watts Output - 4.2.2 Ch|| Powerful Speakers with Dolby Atmos || Surround Sound || Active Voice Amplifier || Adaptive Sound+",
      "Smart TV Features : Mirroring || Tap View ||Multi-View || Music Wall || Mobile Camera Support || Wireless Dex || Auto Game Mode (ALLM) || Game Motion Plus || Dynamic Black EQ || Surround Sound || Super Ultra Wide Game View ||Mini Map Zoom || FreeSync Premium Pro || HGiG",
      "Up to 28 hours of video playback, the best battery life ever in an iPhone Durable design with Ceramic Shield",
      "Industry-leading IP68 water resistance",
      "Easy Returns: This product is eligible for replacement within 10 days of delivery in case of any product defects, damage or features not matching the description",
      " Supports MagSafe accessories for easy attachment and faster wireless charging",
      "Industry-leading IP68 water resistance",
      "Warranty Information: 1 year comprehensive warranty plus additional 1 years on panel by brand from date of invoice",
    ],
    otherOffer: "₹10000 off on exchange of old television",
    rating: {
      rate: 4,
      count: 5665,
      answers: 163,
    },
  },
  {
    id: 4,
    title: "Rolex Ceramic Automatic dial Men's Watch(Imported)",
    price: { offer: "210000.00", mrp: "255000", exchange: "25000.00" },
    emi: "10000",
    image: "https://i.ibb.co/sFqH5BF/rolexwatch.png",
    description: [
      "Strap Material: Metal, Strap Colour: silver",
      "Movement type: Automatic, water Resistance:30 meter",
      "5 ATM Water-resistance",
      "Warranty: 6 month warranty of machine",
      "Dial Diameter:42.5, Dial Material: Ceramic",
      "Vibrant Watch Face",
      "High Quality Fashionable Designer Submarine ceramic Dial Metal Chain",
      "Amazing Price Comes in A Brand Box as Complimentary!",
      "Strap Size can be adjusted at any local watch repair shop near your home",
    ],
    otherOffer: "Amazon Fulfilled | FREE Delivery.",
    rating: {
      rate: 5,
      count: 554,
      answers: 455,
    },
  },
  {
    id: 5,
    title: "JBL Ultra Beats UT789 headphones by Harman",
    price: { offer: "20000.00", mrp: "22000.00", exchange: "2000.00" },
    emi: "1686",
    image: "https://i.ibb.co/gzxfzfX/jblheadphones-1.png",
    description: [
      "17 cm (6.7-inch) Super Retina XDR display with ProMotion for a faster, more responsive feel",

      "Superior listening experience with JBL Pure Bass sound. Inline Remote :Yes",
      "Wireless Bluetooth Streaming",
      "11 hours of playtime under optimum audio settings",
      "Call and music controls on earcup",
      "Flat-foldable, lightweight and comfortable",
      "iOS 15 packs new features to do more with iPhone than ever before",
      " Supports MagSafe accessories for easy attachment and faster wireless charging",
      "Industry-leading IP68 water resistance",
      "What's in the box : 1 pair of T460BT headphone, 1 x Charging cable, 1 x Warning Card, 1 x Warranty card, 1 x Safety card, 1 x QSG",
    ],
    otherOffer: "₹5000 off on payment via Amazon Pay",
    rating: {
      rate: 3,
      count: 2114,
      answers: 626,
    },
  },
  {
    id: 6,
    title: "Apple AirPods Pro (5nd Generation)​​​​​​​ - white",
    price: { offer: "32000.00", mrp: "35000.00", exchange: "5000.00" },
    emi: "2,964",
    image: "https://i.ibb.co/y533ByT/appleearbuds.png",
    description: [
      "Active Noise Cancellation reduces unwanted background noise",
      "Adaptive Transparency lets outside sounds in while reducing loud environmental noise",
      "Personalised Spatial Audio with dynamic head tracking places sound all around you",
      "Playback- Enjoy an extended break on weekends with your favourite episodes on stream, virtue of a playback time of up to 42 hours including the 6 hours nonstop playtime for earbuds. Frequency 20Hz-20KHz",
      "Low Latency- Our BEAST mode makes these true wireless earbuds a partner in entertainment with real-time audio and low latency experience.",
      "IP Rating- The earbuds' body comes protected with IPX4 rating for water and sweat resistance.",
      "Voice Assistant- You can summon your default voice assistant(s) with ease via its One Touch Voice",
      " Supports MagSafe accessories for easy attachment and faster wireless charging",
      "Industry-leading IP68 water resistance",
      "1 year warranty from the date of purchase",
    ],
    otherOffer: "Amazon Fulfilled | FREE Delivery.",
    rating: {
      rate: 4,
      count: 3335,
      answers: 295,
    },
  },
  {
    id: 7,
    title: "Echo Dot (4th Gen, 2020 release)| Smart speaker with Alexa (Blue)",
    price: { offer: "44000.00", mrp: "45500.00", exchange: "4000.00" },
    emi: "5000",
    image: "https://i.ibb.co/71zmbdD/alexa.webp",
    description: [
      "Echo Dot is a smart speaker that can be operated by voice - even from distance. Alexa can speak both English & Hindi, and new features are added automatically",
      "Echo Dot (4th Gen) with clock has a new spherical design and improved bass performance compared to Echo Dot (3rd Gen)",
      "Comes with an LED display that shows time, outdoor temperature or timers. Tap the top to snooze. The light sensor automatically adjusts the display’s brightness, day or night.",
      "Hands-free music control: Stream millions of songs in your favorite language from Amazon Prime Music, Spotify, JioSaavn, Gaana, or Apple Music",
      "Versatile usage: use Echo Dot as a standalone speaker or connect it to other speakers/headphones to enjoy audio on your favorite devices. Or simply pair your phone with Echo Dot and use it as a Bluetooth speaker",
      "Get started with Smart home: It is simple to make your home smart and use voice to control lights, ACs, TVs, geysers, water motors and more",
      "Voice makes everything simple: Just ask Alexa to easily pay your bills, get news, weather, cricket scores, nursery rhymes and stories!",
      "1 year warranty from the date of purchase",
      "Industry-leading IP68 water resistance",
      "Suitable for smart homes",
    ],
    otherOffer: "₹15000 off on payment via Amazon Pay",
    rating: {
      rate: 4,
      count: 5456,
      answers: 45,
    },
  },
  {
    id: 8,
    title: "Asian Men's Cosko Sports Running,Walking,Gym,Training Sneaker",
    price: { offer: "3000.00", mrp: "3500.00", exchange: "250.00" },
    emi: "750",
    image: "https://i.ibb.co/7VR6pb6/sportshoe.png",
    description: [
      "Upper Material- Mesh",
      "Sole Material-Eva; Closure: Lace Up",
      "Water-resistance",
      "Lifestyle: Sports",
      "Care Instructions: Wipe with a clean, dry cloth when needed",
      "Do not wash with detergent or in washing machine",
      "Super Slim & Light weighted",
      "Age Range Description: Adult; Department Name: Mens; Toe Style: Round Toe; Pattern Type: Solid",
      "6 months warranty period",
    ],
    otherOffer: "Amazon Fulfilled | FREE Delivery.",
    rating: {
      rate: 2,
      count: 154,
      answers: 67,
    },
  },
  {
    id: 9,
    title: "Apple iPhone 13 Pro",
    price: { offer: "1,15,000", mrp: "1,20,000", exchange: "16000" },
    emi: "5,456",
    image: "https://i.ibb.co/gWGSJKF/hilfigerwallet.png",
    description: [
      "17 cm (6.7-inch) Super Retina XDR display with ProMotion for a faster, more responsive feel",
      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Pro camera system with new 12MP Telephoto, Wide and Ultra Wide cameras; LiDAR Scanner; 6x optical zoom range; macro photography; Photographic Styles, ProRes video, Smart HDR 4, Night mode, Apple ProRAW, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording A15 Bionic chip for lightning - fast performance",
      "Up to 28 hours of video playback, the best battery life ever in an iPhone Durable design with Ceramic Shield",
      "Industry-leading IP68 water resistance",
      "iOS 15 packs new features to do more with iPhone than ever before",
      " Supports MagSafe accessories for easy attachment and faster wireless charging",
      "Industry-leading IP68 water resistance",
      "form_factor:Smartphone,operating_system:iOS 14",
    ],
    otherOffer: "₹11.49 with Subscribe & Save discount",
    rating: {
      rate: 4,
      count: 645,
      answers: 215,
    },
  },
  {
    id: 10,
    title: "Amazfit Bip 3 Smart Watch with 1.69 Large Color Display",
    price: { offer: "4,000", mrp: "4,500", exchange: "16000" },
    emi: "500",
    image: "https://i.ibb.co/qdG7sGj/formalshoe.png",
    description: [
      "1.69 inch Large Color Display",
      "2 Weeks' Battery Life",
      "5 ATM Water-resistance",
      "60 Sports Modes",
      "Blood-oxygen Saturation Measurement",
      "50+ Vibrant Watch Faces",
      "Super Slim & Light Body",
      "Monitoring of Heart Rate, Stress Levels & Sleep",
      "PAI Health Assessment System",
    ],
    otherOffer: "₹11.49 with Subscribe & Save discount",
    rating: {
      rate: 4,
      count: 1454,
      answers: 45,
    },
  },
  {
    id: 11,
    title: "Apple iPhone 13 Pro (512GB) - Sierra Blue",
    price: { offer: "1,15,000.00", mrp: "1,20,000.00", exchange: "16000" },
    emi: "5,456",
    image: "https://i.ibb.co/MBHJmvB/casualshirt.png",
    description: [
      "17 cm (6.7-inch) Super Retina XDR display with ProMotion for a faster, more responsive feel",

      "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
      "Pro camera system with new 12MP Telephoto, Wide and Ultra Wide cameras; LiDAR Scanner; 6x optical zoom range; macro photography; Photographic Styles, ProRes video, Smart HDR 4, Night mode, Apple ProRAW, 4K Dolby Vision HDR recording",
      "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording A15 Bionic chip for lightning - fast performance",
      "Up to 28 hours of video playback, the best battery life ever in an iPhone Durable design with Ceramic Shield",
      "Industry-leading IP68 water resistance",
      "iOS 15 packs new features to do more with iPhone than ever before",
      " Supports MagSafe accessories for easy attachment and faster wireless charging",
      "Industry-leading IP68 water resistance",
      "form_factor:Smartphone,operating_system:iOS 14",
    ],
    otherOffer: "₹11.49 with Subscribe & Save discount",
    rating: {
      rate: 4,
      count: 654,
      answers: 215,
    },
  },
  {
    id: 12,
    title: "Amazfit Bip 3 Smart Watch with 1.69 Large Color Display",
    price: { offer: "4,000", mrp: "4,500", exchange: "16000" },
    emi: "500",
    image: "https://i.ibb.co/ZV1jqn7/canoncamera.png",
    description: [
      "1.69 inch Large Color Display",
      "2 Weeks' Battery Life",
      "5 ATM Water-resistance",
      "60 Sports Modes",
      "Blood-oxygen Saturation Measurement",
      "50+ Vibrant Watch Faces",
      "Super Slim & Light Body",
      "Monitoring of Heart Rate, Stress Levels & Sleep",
      "PAI Health Assessment System",
    ],
    otherOffer: "Amazon Fulfilled | FREE Delivery.",
    rating: {
      rate: 4,
      count: 1454,
      answers: 45,
    },
  },
];

export default productData;
