let adBoxData = [
  {
    id: "1",
    type: "one",
    header: "Echo Dot | Movies, music & more.",
    images: ["https://i.ibb.co/p4x0PDr/alexa.jpg"],
  },
  {
    id: "2",
    type: "two",
    header: "Shop by Category",
    images: [
      "https://i.ibb.co/ChSZTF4/mobile.webp",
      "https://i.ibb.co/K9k88T0/dressing.webp",
      "https://i.ibb.co/BZWHnj9/electronics.webp",
      "https://i.ibb.co/s1kzWgM/food.jpg",
    ],
    imageTitle: ["Mobiles", "Fashion", "Electronics", "Fresh"],
  },
  {
    id: "3",
    type: "two",
    header: "Upto 20% off on all electronics",
    images: [
      "https://i.ibb.co/cv60Kz2/televisions.jpg",
      "https://i.ibb.co/xXBrc7x/watches.jpg",
      "https://i.ibb.co/pdgSgjT/cameras.jpg",
      "https://i.ibb.co/QJ6mVvN/headphones.jpg",
    ],
    imageTitle: ["Television", "Smartwatches", "Cameras", "Headphones"],
  },
  {
    id: "4",
    type: "",
    header: "",
    images: [""],
  },
  {
    id: "5",
    type: "two",
    header: "Shop by Category | Fashion and more",
    images: [
      "https://i.ibb.co/1RHRhMC/shirts.jpg",
      "https://i.ibb.co/YZH1Y1G/shoes.jpg",
      "https://i.ibb.co/QND0gbg/watches-analog.jpg",
      "https://i.ibb.co/py0y7w2/purse.jpg",
    ],
    imageTitle: ["Clothes", "Shoes", "Wristwatch", "Wallets"],
  },
  {
    id: "6",
    type: "two",
    header: "Amazon Pay | Book your travel tickets",
    images: [
      "https://i.ibb.co/Bf4szjx/flights.jpg",
      "https://i.ibb.co/wdpzrzJ/buses.jpg",
      "https://i.ibb.co/4gVkRn1/trains.jpg",
      "https://i.ibb.co/6PJdjFX/travel-bags.jpg",
    ],
    imageTitle: [
      "Flight tickets",
      "Bus tickets",
      "Train tickets",
      "Essential travel products",
    ],
  },
  {
    id: "7",
    type: "one",
    header: "Upto 70% off | Beauty products clearance store",
    images: ["https://i.ibb.co/mTxGDsY/beauty-items.jpg"],
  },
  {
    id: "8",
    type: "two",
    header: "Join Prime to access epic deals on Prime Day",
    images: [
      "https://i.ibb.co/x2fwvrP/deals.jpg",
      "https://i.ibb.co/f8H9J5Y/freeshipping.jpg",
      "https://i.ibb.co/ft7TCDd/homeservice.jpg",
      "https://i.ibb.co/VpJq6Tb/globalstore.jpg",
    ],
    imageTitle: [
      "Exclusive deals",
      "Free shipping",
      "Easy home services",
      "Free global shipping",
    ],
  },
  {
    id: "9",
    type: "three",
    header: "",
    images: [
      " https://i.ibb.co/xG39L2M/earbud-black.jpg",
      "https://i.ibb.co/nrDffK1/earbud-white.jpg",
      "https://i.ibb.co/wy14wL8/football.jpg",
      "https://i.ibb.co/HDb11Kf/pendrive.jpg",
      "https://i.ibb.co/YDWvQrC/phone.jpg",
      "https://i.ibb.co/sFNzLjc/router.jpg",
      "https://i.ibb.co/F5bCTpQ/bottle.jpg",
      "https://i.ibb.co/vkmyjXR/yonex-cock.jpg",
      "https://i.ibb.co/YLYMdP0/yoga-mat.jpg",
      "https://i.ibb.co/QFqSGYv/weighing-machine.jpg",
    ],
  },
  {
    id: "10",
    type: "one",
    header: "Free delivery on your first eligible order",
    images: ["https://i.ibb.co/bBrxxzz/free-shipping.jpg"],
  },
  {
    id: "11",
    type: "one",
    header: "Upto 30% off on kitchen essentials",
    images: ["https://i.ibb.co/HF9RkmR/kitchen-items.jpg"],
  },
  {
    id: "12",
    type: "two",
    header: "Electronic devices for home office",
    images: [
      "https://i.ibb.co/Br0v2yg/kindle.jpg",
      "https://i.ibb.co/16Z6gc3/tablet.jpg",
      "https://i.ibb.co/bdjSmnR/ipads.jpg",
      "https://i.ibb.co/nDvzMQZ/digitalnotes.jpg",
    ],
    imageTitle: ["Kindle", "Tablets", "Ipods", "Digital notepad"],
  },
  {
    id: "13",
    type: "one",
    header: "Upto 40% off | Carpentry store",
    images: ["https://i.ibb.co/GPGzzxk/carpentary.jpg"],
  },
  {
    id: "14",
    type: "four",
    header: "",
    images: ["https://i.ibb.co/ZHhLhVy/gift-card.jpg"],
  },
  {
    id: "15",
    type: "three",
    header: "",
    images: [
      "https://i.ibb.co/X4znr7N/knee-cap.jpg",
      "https://i.ibb.co/2gH4XsT/hp-ink.jpg",
      "https://i.ibb.co/HPBqhgZ/bag.jpg",
      "https://i.ibb.co/48V3Dtd/can-opener.jpg",
      "https://i.ibb.co/DDWB0FC/cooking-vessel.jpg",
      "https://i.ibb.co/Wc0jF7s/lazar.jpg",
      "https://i.ibb.co/2Kr3WV8/phone.jpg",
      "https://i.ibb.co/NswxBzp/laptop-stand.jpg",
      "https://i.ibb.co/hygxH6d/skipping-rope.jpg",
      "https://i.ibb.co/JxcFbqB/badminton-racket.jpg",
    ],
  },
];

export default adBoxData;
